# Generated by Django 2.2.6 on 2019-11-13 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191113_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='loke_users',
            new_name='like_users',
        ),
    ]
